/**
 * This file is auto-generated by the build script.
 * It consolidates API functions for use in the application.
 * Do not edit manually.
 */
import edge_add from './src/edge/add.js';
import edge_addMultiple from './src/edge/addMultiple.js';
import edge_delete from './src/edge/delete.js';
import edge_deleteMultiple from './src/edge/deleteMultiple.js';
import edge_get from './src/edge/get.js';
import edge_getMultiple from './src/edge/getMultiple.js';
import edge_search from './src/edge/search.js';
import kv_add from './src/kv/add.js';
import kv_addMultiple from './src/kv/addMultiple.js';
import kv_delete from './src/kv/delete.js';
import kv_deleteMultiple from './src/kv/deleteMultiple.js';
import kv_get from './src/kv/get.js';
import kv_getMultiple from './src/kv/getMultiple.js';
import utils_config from './src/utils/config.js';
import utils_createDB from './src/utils/createDB.js';
import utils_pool from './src/utils/pool.js';
import vertex_add from './src/vertex/add.js';
import vertex_addMultiple from './src/vertex/addMultiple.js';
import vertex_delete from './src/vertex/delete.js';
import vertex_deleteMultiple from './src/vertex/deleteMultiple.js';
import vertex_get from './src/vertex/get.js';
import vertex_getMultiple from './src/vertex/getMultiple.js';
import vertex_search from './src/vertex/search.js';


export default {
    edge: {
        add: edge_add,
        addMultiple: edge_addMultiple,
        delete: edge_delete,
        deleteMultiple: edge_deleteMultiple,
        get: edge_get,
        getMultiple: edge_getMultiple,
        search: edge_search
    },
    kv: {
        /**
        * Adds a key-value pair to the storage.
        *
        * @param {string} key - The key to add.
        * @param {string} value - The value to associate with the key.
        * @returns {Promise<void>} A promise that resolves when the key-value pair has been added.
        */
        add: kv_add,
        /**
         * Adds multiple key-value pairs to the database.
         * 
         * @example graph.kv.addMultiple({
         *    key1: { some: 'data' },
         *    key2: 'some string'
         * });
         *
         * @param {Object} dictionary - An object containing key-value pairs to be added.
         * @param {Object} options - Options for the batch insertion.
         * @param {number} [options.batchSize=settings.defaultBatchSize] - The number of key-value pairs to insert in each batch.
         * @returns {Promise<Object>} - The original dictionary object.
         * @throws {Object} - Throws an error if a key is invalid or if the database insertion fails.
         */
        addMultiple: kv_addMultiple,
        delete: kv_delete,
        deleteMultiple: kv_deleteMultiple,
        get: kv_get,
        getMultiple: kv_getMultiple
    },
    utils: {
        config: utils_config,
        createDB: utils_createDB,
        pool: utils_pool
    },
    vertex: {
        /**
         * Adds a single vertex to the graph.
         *
         * @param {Object} vertex - The vertex object to be added.
         * @param {string} vertex._type - The type of the vertex.
         * @param {string} vertex._id - The ID of the vertex. If not provided, a UUID will be generated.
         * @returns {Promise<Object>} A promise that resolves to the added vertex.
         */
        add: vertex_add,
        /**
         * Adds multiple vertices to the database.
         * 
         * @example graph.vertices.addMultiple([
         *    { _id: 'this uuid will be used', _type: 'Person', name: 'Alice' },
         *    { _type: 'City', name: 'Wonderland' } // id will be generated
         * ]);
         *
         * @param {Array<Object>} vertices - An array of vertex objects to be added.
         * @param {Object} options - Options for the batch insertion.
         * @param {number} [options.batchSize=settings.defaultBatchSize] - The number of vertices to insert in each batch.
         * @returns {Promise<Array>} - An array of inserted vertex IDs.
         * @throws {Object} - Throws an error if a vertex type is invalid or if the database insertion fails.
         */
        addMultiple: vertex_addMultiple,
        delete: vertex_delete,
        deleteMultiple: vertex_deleteMultiple,
        get: vertex_get,
        getMultiple: vertex_getMultiple,
        search: vertex_search
    }
};